# Generated by Django 2.2.3 on 2019-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_no',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
