# Generated by Django 2.2.3 on 2019-10-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190925_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='user',
        ),
    ]
