# Generated by Django 2.2.3 on 2019-10-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_profile',
        ),
    ]
