# Generated by Django 2.2.3 on 2019-10-29 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191009_0932'),
        ('products', '0010_product_store_name'),
        ('addresses', '0004_auto_20191024_1906'),
        ('orders', '0002_remove_order_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Address')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
    ]
