# Generated by Django 2.2.3 on 2019-11-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191103_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placed',
            old_name='date_added',
            new_name='date_placed',
        ),
    ]
