# Generated by Django 2.2.3 on 2019-11-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_placed_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed',
            name='order_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
