# Generated by Django 2.2.3 on 2019-10-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191009_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(max_length=120),
        ),
    ]
