# Generated by Django 2.2.3 on 2019-10-09 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191009_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
