# Generated by Django 2.2.3 on 2019-10-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('products', '0009_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.SET_DEFAULT, to='store.Store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Product', max_length=120),
        ),
    ]
