# Generated by Django 2.2.3 on 2019-10-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191009_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_name',
            field=models.CharField(default='None', max_length=120),
        ),
    ]
