# Generated by Django 2.2.3 on 2019-11-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jewellery', 'Jewellery'), ('homedecor', 'Home Decor'), ('clothing', 'Clothing')], max_length=120),
        ),
    ]
