# Generated by Django 2.2.3 on 2019-10-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('products', '0011_remove_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
