# Generated by Django 2.2.3 on 2019-10-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
